name: Eufemia Actions

on:
  push:
    branches:
      - '**'
      - '!**--skip-ci'
      - '!**--visual-reports'
      - '!wip/**'
      - '!experiments/**'

jobs:
  action:
    name: Test and Deploy

    runs-on: macos-latest

    env:
      GH_EMAIL: ${{ secrets.GH_EMAIL }}
      GH_NAME: ${{ secrets.GH_NAME }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      FIGMA_ICONS_FILE: ${{ secrets.FIGMA_ICONS_FILE }}
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
      ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}
      ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.0

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Use yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Audit dependencies
        run: yarn workspace @dnb/eufemia audit:ci

      - name: Run lint
        run: yarn workspace @dnb/eufemia lint:ci && yarn workspace dnb-design-system-portal lint:ci

      - name: Run tests
        run: yarn workspace @dnb/eufemia test:ci && yarn workspace dnb-design-system-portal test:ci

      - name: Icons fetch and prebuild
        if: github.ref == 'refs/heads/eufemia-icons'
        run: yarn workspace @dnb/eufemia prebuild:figma:ci

      - name: Prebuild Library
        run: yarn workspace @dnb/eufemia prebuild:ci

      - name: Get current date
        id: date
        run: echo "::set-output name=timestamp::$(date +'%Y-%U')"

      - name: Use Gatsby cache
        uses: actions/cache@v2
        id: gatsby-cache
        with:
          path: |
            ./packages/dnb-design-system-portal/.cache
            ./packages/dnb-design-system-portal/public
          key: ${{ runner.os }}-gatsby-${{ hashFiles('**/yarn.lock') }}-${{ steps.date.outputs.timestamp }}

      - name: Build portal
        run: yarn workspace dnb-design-system-portal build-ci

      - name: Run visual tests
        if: runner.os == 'macOS' &&
          (!contains(github.ref, '/release') && !contains(github.ref, '/main') && !contains(github.ref, '/portal') && !contains(github.ref, '/eufemia-icons') && !contains(github.ref, '/beta') && !contains(github.ref, '/alpha'))
        run: yarn workspace @dnb/eufemia test:screenshots:ci

      - name: Icons postbuild
        if: github.ref == 'refs/heads/eufemia-icons'
        run: yarn workspace @dnb/eufemia postbuild:figma:ci

      - name: Lib postbuild
        if: (contains(github.ref, '/main') ||
          contains(github.ref, '/release') ||
          contains(github.ref, '/beta') ||
          contains(github.ref, '/alpha'))
        run: yarn workspace @dnb/eufemia postbuild:ci

      # - name: Deploy portal (drone.io)
      #   if: (contains(github.ref, '/release') ||
      #     contains(github.ref, '/portal'))
      #   run: yarn workspace dnb-design-system-portal deploy-ci

      - name: Deploy portal
        if: (contains(github.ref, '/release') ||
          contains(github.ref, '/portal'))
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./packages/dnb-design-system-portal/public

      - name: Release
        if: (contains(github.ref, '/release') ||
          contains(github.ref, '/beta') ||
          contains(github.ref, '/alpha'))
        run: yarn workspace @dnb/eufemia publish:ci

      - name: Slack
        uses: 8398a7/action-slack@v3
        with:
          channel: '#eufemia-dev'
          status: ${{ job.status }}
          fields: commit,repo,ref,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always()
